AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   CFN Template To Create A S3 Table With Or Without A Folder. 

Metadata:
  TemplateName: s3-stack.yaml
  TemplateType: S3 bucket with optionally default folder
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Standardization
  Modification History:
    - 1.0.0  - December 10, 2022   -- Initial Version 
  Resources: 
    - S3 Bucket
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyAlias
    - Label:
        default: "S3 Configuration:"
      Parameters:
      - S3BucketBaseName
      - S3DataBucketFolder
      - S3BucketBlockPublicAcls
      - S3BucketBlockPublicPolicy
      - S3BucketIgnorePublicAcls
      - S3BucketRestrictPublicBuckets
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ############################################ KMS ###############################################
      KmsMasterKeyAlias: 
        default: "The KMS Master Key Alias To Be Used For Server Side Encryption."
      ########################################### S3 Bucket and Folder ###############################
      S3BucketBaseName:
        default: "S3 Bucket Base Name."
      S3DataBucketFolder:
        default: "The folder(s) to be created."
      S3BucketBlockPublicAcls:
        default: "Allow BlockPublicAcls"
      S3BucketBlockPublicPolicy:
        default: "Allow BlockPublicPolicy"
      S3BucketIgnorePublicAcls:
        default: "Allow IgnorePublicAcls"
      S3BucketRestrictPublicBuckets:
        default: "Allow restrictPublicBuckets"
Parameters:
  ########################################### Project Name and Environment #######################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod" 
  ############################################ KMS ###############################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ########################################### S3 Bucket and Folder ###############################
  S3BucketBaseName:
    Default: some-s3-bucket-name
    Description: "The S3 Bucket Base Name For The Source Data, The Region Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  S3DataBucketFolder:
    Default: "inbound,outbound"
    Description: "The Folder To Be Created For Stroing The Raw Data. Use do_not_create If You Do Not Want To Create Any Folder."
    Type: CommaDelimitedList
    ConstraintDescription: "Should be a comma seperated folder names."  
  S3BucketBlockPublicAcls:
    Default: true
    Description: "Allow Block Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketBlockPublicPolicy:
    Default: true
    Description: "Allow Block Public Policy"
    Type: String
    AllowedValues: [true, false]
  S3BucketIgnorePublicAcls:
    Default: true
    Description: "Allow Ignore Public Acls"
    Type: String
    AllowedValues: [true, false]
  S3BucketRestrictPublicBuckets:
    Default: true
    Description: "Allow Restrict Public Buckets"
    Type: String
    AllowedValues: [true, false]
  S3CustomResourceStackName:
    Default: "s3-custom-resource-stack"
    Description: "S3 Custom Resource Stack Name"
    Type: String
Resources:
  ############################################ S3 Bucket ##########################################
  S3IntegrationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${S3BucketBaseName}-${Environment}-${AWS::Region}"
      BucketEncryption:
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Sub 'alias/${KmsMasterKeyAlias}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref S3BucketBlockPublicAcls
        BlockPublicPolicy: !Ref S3BucketBlockPublicPolicy
        IgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        RestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
  S3DataBucketCustomResource:
    Type: Custom::S3CustomResource
    Properties:
      ServiceToken: 
        Fn::ImportValue: !Sub '${S3CustomResourceStackName}-S3CreateFolderCustomResourceLambdaFunctionArn' 
      bucket_name: !Ref S3IntegrationBucket
      folders_to_create: !Ref S3DataBucketFolder
Outputs:
  S3IntegrationBucketArn:
    Description: The endpoint of the S3 integration bucket.
    Value: !GetAtt S3IntegrationBucket.Arn
